openapi: 3.0.0
info:
  title: Authentication API
  version: 1.0.0
  description: API specification for the Better Auth authentication system with Neon Postgres
servers:
  - url: http://localhost:3000
    description: Development server
  - url: https://your-production-domain.com
    description: Production server
paths:
  /api/auth/signup:
    post:
      summary: Create a new user account
      description: Register a new user with email and password
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                  description: User's email address
                  example: user@example.com
                password:
                  type: string
                  format: password
                  description: User's password (min 8 characters)
                  example: securePassword123
                firstName:
                  type: string
                  description: User's first name (optional)
                  example: John
                lastName:
                  type: string
                  description: User's last name (optional)
                  example: Doe
      responses:
        '200':
          description: User successfully created and logged in
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    $ref: '#/components/schemas/User'
                  session:
                    $ref: '#/components/schemas/Session'
                  message:
                    type: string
                    example: "User created and logged in successfully"
        '400':
          description: Bad request - invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '409':
          description: Conflict - email already exists
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /api/auth/login:
    post:
      summary: Authenticate user and create session
      description: Login with email and password
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                  example: user@example.com
                password:
                  type: string
                  format: password
                  example: securePassword123
      responses:
        '200':
          description: User successfully authenticated
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    $ref: '#/components/schemas/User'
                  session:
                    $ref: '#/components/schemas/Session'
                  message:
                    type: string
                    example: "Login successful"
        '400':
          description: Bad request - invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized - invalid credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /api/auth/me:
    get:
      summary: Get current user information
      description: Retrieve information about the authenticated user
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Current user information
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    $ref: '#/components/schemas/User'
        '401':
          description: Unauthorized - invalid or expired session
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /api/auth/oauth/google:
    get:
      summary: Initiate Google OAuth flow
      description: Redirect user to Google for authentication
      responses:
        '302':
          description: Redirect to Google OAuth
  /api/auth/oauth/github:
    get:
      summary: Initiate GitHub OAuth flow
      description: Redirect user to GitHub for authentication
      responses:
        '302':
          description: Redirect to GitHub OAuth
  /api/auth/logout:
    post:
      summary: End user session
      description: Logout user and clear session
      responses:
        '200':
          description: Successfully logged out
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Logged out successfully"
        '401':
          description: Unauthorized - no active session
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /api/auth/session:
    get:
      summary: Get current session information
      description: Retrieve current session and user information for client-side validation
      responses:
        '200':
          description: Current session information
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    $ref: '#/components/schemas/User'
                  session:
                    $ref: '#/components/schemas/Session'
        '401':
          description: Unauthorized - invalid or expired session
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /api/protected/profile:
    get:
      summary: Get user profile (protected route example)
      description: Example of a protected route requiring authentication
      security:
        - bearerAuth: []
      responses:
        '200':
          description: User profile information
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    $ref: '#/components/schemas/User'
                  message:
                    type: string
                    example: "This is a protected route. You are authenticated."
        '401':
          description: Unauthorized - invalid or expired session
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
          description: Unique user identifier
          example: "user_1234567890"
        email:
          type: string
          format: email
          description: User's email address
          example: user@example.com
        emailVerified:
          type: boolean
          description: Whether the email has been verified
          example: false
        firstName:
          type: string
          description: User's first name
          example: John
        lastName:
          type: string
          description: User's last name
          example: Doe
        createdAt:
          type: string
          format: date-time
          description: When the user account was created
          example: "2023-01-01T00:00:00.000Z"
        updatedAt:
          type: string
          format: date-time
          description: When the user account was last updated
          example: "2023-01-01T00:00:00.000Z"
    Session:
      type: object
      properties:
        id:
          type: string
          description: Unique session identifier
          example: "sess_1234567890"
        userId:
          type: string
          description: ID of the user this session belongs to
          example: "user_1234567890"
        expiresAt:
          type: string
          format: date-time
          description: When the session expires
          example: "2023-01-02T00:00:00.000Z"
        createdAt:
          type: string
          format: date-time
          description: When the session was created
          example: "2023-01-01T00:00:00.000Z"
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          description: Error message
          example: "Invalid email format"
        code:
          type: string
          description: Error code
          example: "INVALID_EMAIL"